import { Notice, CalendarEvent, Assignment, AppUser } from './types';

function daysFromNow(days: number): Date {
  const d = new Date();
  d.setDate(d.getDate() + days);
  d.setHours(0, 0, 0, 0);
  return d;
}

function daysAgo(days: number): Date {
  const d = new Date();
  d.setDate(d.getDate() - days);
  return d;
}

export const SEED_NOTICES: Omit<Notice, 'id'>[] = [
  // ACADEMIC (6)
  {
    title: 'BBA Semester 8: Provisional Timetable (Even Sem 2025-26)',
    body: 'The provisional timetable for Semester 8 (Sections A, B, C) has been uploaded. Classes will commence on June 15th. Major subjects include Strategic Management and International Business. Please check your assigned rooms in Block B.',
    category: 'Academic',
    tags: ['BBA-4', 'ALL'],
    urgency: 'Urgent',
    postedBy: 'Dr. Rajesh Kumar Sharma',
    postedAt: daysAgo(1),
    expiryDate: daysFromNow(30),
    isPinned: true,
    attachmentUrl: null,
    attachmentName: 'BBA_Sem8_Timetable.pdf',
  },
  {
    title: 'Research Project (BBA805): Synopsis Submission Deadline',
    body: 'All final year students must submit their research synopses for approval by July 5th. Please ensure your guide has signed the hard copy before submission to the HOD office. Format is available on the portal.',
    category: 'Academic',
    tags: ['BBA-4'],
    urgency: 'Important',
    postedBy: 'Prof. Anita Gupta',
    postedAt: daysAgo(2),
    expiryDate: daysFromNow(10),
    isPinned: false,
    attachmentUrl: null,
    attachmentName: null,
  },
  {
    title: 'Library: Final Year Clearance Policy',
    body: 'Students graduating in 2026 must clear all pending library dues by the end of this month to receive their No-Dues certificate. Defaulting students will not be issued their final semester hall tickets.',
    category: 'Academic',
    tags: ['ALL'],
    urgency: 'Normal',
    postedBy: 'Chief Librarian',
    postedAt: daysAgo(5),
    expiryDate: daysFromNow(45),
    isPinned: false,
    attachmentUrl: null,
    attachmentName: null,
  },
  {
    title: 'Special Guest Lecture: AI in Strategic Management',
    body: 'Join us for an insightful session by Mr. Vikram Aditya (VP, TechMahindra) on how AI is reshaping corporate strategy. Date: July 12th, 10 AM, Auditorium A. Mandatory for all BBA 4th year students.',
    category: 'Academic',
    tags: ['BBA-4'],
    urgency: 'Normal',
    postedBy: 'Dept. Coordinator',
    postedAt: daysAgo(3),
    expiryDate: daysFromNow(15),
    isPinned: false,
    attachmentUrl: null,
    attachmentName: null,
  },
  {
    title: 'Moot Court Competition Selection',
    body: 'Selection trials for the SAGI Inter-University Moot Court team will be held on July 8th. Interested BBA-LLB students should register at the Law Faculty desk by July 6th.',
    category: 'Academic',
    tags: ['ALL'],
    urgency: 'Normal',
    postedBy: 'Prof. Suresh Verma',
    postedAt: daysAgo(4),
    expiryDate: daysFromNow(8),
    isPinned: false,
    attachmentUrl: null,
    attachmentName: null,
  },
  {
    title: 'Remedial Classes for Financial Accounting',
    body: 'Special remedial classes for students who scored below 50% in the internal assessment will be held every Saturday at 2 PM. Please enroll with the department clerk.',
    category: 'Academic',
    tags: ['BBA-4'],
    urgency: 'Normal',
    postedBy: 'Dr. Manish Patel',
    postedAt: daysAgo(7),
    expiryDate: daysFromNow(60),
    isPinned: false,
    attachmentUrl: null,
    attachmentName: null,
  },

  // PLACEMENT (6)
  {
    title: 'HDFC Bank: On-Campus Drive for Management Trainees',
    body: 'HDFC Bank is visiting SAGI for Management Trainee roles. Eligibility: BBA/MBA with 60% aggregate. CTC: 6.5 LPA. Pre-placement talk on July 10th. Register on the T&P portal by July 8th.',
    category: 'Placement',
    tags: ['BBA-4', 'ALL'],
    urgency: 'Urgent',
    postedBy: 'Placement Cell',
    postedAt: daysAgo(1),
    expiryDate: daysFromNow(11),
    isPinned: true,
    attachmentUrl: null,
    attachmentName: 'HDFC_JD.pdf',
  },
  {
    title: 'Placement Workshop: Cracking Case Study Interviews',
    body: 'A hands-on workshop on solving case study-based interview questions by Deloitte consultants. Time: July 15th, 2 PM to 5 PM in Seminar Hall 1. Limited seats (120) - first come first serve.',
    category: 'Placement',
    tags: ['ALL'],
    urgency: 'Important',
    postedBy: 'Placement Cell',
    postedAt: daysAgo(2),
    expiryDate: daysFromNow(16),
    isPinned: false,
    attachmentUrl: null,
    attachmentName: null,
  },
  {
    title: 'Byju\'s Recruitment Results - Batch 2026',
    body: 'Congratulations to the 14 students selected as BDA interns from the drive held on June 28th. Offer letters will be dispatched via email by end of week. Visit T&P for the full list.',
    category: 'Placement',
    tags: ['ALL'],
    urgency: 'Normal',
    postedBy: 'Placement Cell',
    postedAt: daysAgo(3),
    expiryDate: daysFromNow(20),
    isPinned: false,
    attachmentUrl: null,
    attachmentName: null,
  },
  {
    title: 'LinkedIn Optimization & Networking Session',
    body: 'Learn how to build a professional LinkedIn profile and network effectively with SAGI alumni. Guest speaker: Ms. Sneha Jain (HR Lead, Reliance). July 20th, 11 AM.',
    category: 'Placement',
    tags: ['ALL'],
    urgency: 'Normal',
    postedBy: 'Placement Cell',
    postedAt: daysAgo(5),
    expiryDate: daysFromNow(21),
    isPinned: false,
    attachmentUrl: null,
    attachmentName: null,
  },
  {
    title: 'Mock GD/PI Sessions for Final Year',
    body: 'Mock Group Discussion and Personal Interview sessions will be conducted department-wise next week. BBA slots: Monday and Wednesday. Dress code: Formal mandatory.',
    category: 'Placement',
    tags: ['BBA-4'],
    urgency: 'Important',
    postedBy: 'Placement Cell',
    postedAt: daysAgo(4),
    expiryDate: daysFromNow(14),
    isPinned: false,
    attachmentUrl: null,
    attachmentName: null,
  },
  {
    title: 'PwC Off-Campus Opportunity: Associate Consultant',
    body: 'PwC is hiring for Associate Consultant roles off-campus. Interested 2026 graduates can apply via the referral link shared on our internal telegram group. Deadline: July 25th.',
    category: 'Placement',
    tags: ['ALL'],
    urgency: 'Normal',
    postedBy: 'Placement Cell',
    postedAt: daysAgo(6),
    expiryDate: daysFromNow(26),
    isPinned: false,
    attachmentUrl: null,
    attachmentName: null,
  },

  // EVENTS (5)
  {
    title: "SAGI Founders' Day - Annual Cultural Gala",
    body: "Celebrating 25 years of SAGI Excellence! A grand evening with theater, dance, and a special performance by 'Indian Ocean'. Date: July 28th. Student passes can be collected from the cultural office.",
    category: 'Events',
    tags: ['ALL'],
    urgency: 'Normal',
    postedBy: 'Student Council',
    postedAt: daysAgo(1),
    expiryDate: daysFromNow(29),
    isPinned: true,
    attachmentUrl: null,
    attachmentName: null,
  },
  {
    title: 'Inter-College Business Quiz (B-Quiz 2026)',
    body: "Showcase your business acumen at B-Quiz 2026. Teams of 2. Format: Written round + Final stage round. Prizes worth Rs. 50,000. Registration closes July 20th.",
    category: 'Events',
    tags: ['ALL'],
    urgency: 'Normal',
    postedBy: 'Management Club',
    postedAt: daysAgo(2),
    expiryDate: daysFromNow(21),
    isPinned: false,
    attachmentUrl: null,
    attachmentName: null,
  },
  {
    title: 'NSS Blood Donation Drive',
    body: "Support our community! Join the NSS Blood Donation Camp on July 10th at the Medical Block. All donors receive a certificate and refreshments. Registration starts 9 AM.",
    category: 'Events',
    tags: ['ALL'],
    urgency: 'Important',
    postedBy: 'NSS Unit',
    postedAt: daysAgo(1),
    expiryDate: daysFromNow(11),
    isPinned: false,
    attachmentUrl: null,
    attachmentName: null,
  },
  {
    title: 'Workshop: Film Making & Script Writing',
    body: "The Media Club is organizing a 2-day workshop with National Award-winning director Mr. Sanjay Patil. Entry fee: Rs. 200. Dates: July 22-23. Register at the Media Lab.",
    category: 'Events',
    tags: ['ALL'],
    urgency: 'Normal',
    postedBy: 'Media Club',
    postedAt: daysAgo(4),
    expiryDate: daysFromNow(24),
    isPinned: false,
    attachmentUrl: null,
    attachmentName: null,
  },
  {
    title: 'Alumni Homecoming 2026',
    body: "Reconnect with your seniors! Alumni from the batches of 2010-2020 are visiting. Student interactive session on July 30th, 4 PM at the Central Lawns.",
    category: 'Events',
    tags: ['ALL'],
    urgency: 'Normal',
    postedBy: 'Alumni Association',
    postedAt: daysAgo(5),
    expiryDate: daysFromNow(31),
    isPinned: false,
    attachmentUrl: null,
    attachmentName: null,
  },

  // SCHOLARSHIPS (4)
  {
    title: 'Post-Matric Scholarship (MP Govt): Renewal Deadline',
    body: 'Students who applied last year must submit their renewal forms for 2025-26 by August 15th. Documents required: Income certificate (Current), Passbook copy, and Result card.',
    category: 'Scholarships',
    tags: ['ALL'],
    urgency: 'Urgent',
    postedBy: 'Admin Office',
    postedAt: daysAgo(1),
    expiryDate: daysFromNow(45),
    isPinned: false,
    attachmentUrl: null,
    attachmentName: null,
  },
  {
    title: 'SAGI Merit-Cum-Means Reward 2026',
    body: "Applications invited for SAGI's internal scholarship for students with 8.5+ CGPA and low family income. Max reward: 50% tuition fee waiver. Submit by end of month.",
    category: 'Scholarships',
    tags: ['ALL'],
    urgency: 'Important',
    postedBy: 'Finance Dept.',
    postedAt: daysAgo(3),
    expiryDate: daysFromNow(28),
    isPinned: false,
    attachmentUrl: null,
    attachmentName: null,
  },
  {
    title: 'Reliance Foundation Undergraduate Scholarship',
    body: "Last date to apply for Reliance Foundation Scholarship for First Year students is July 31st. Students from BBA and Engineering are eligible. Apply at reliancefoundation.org.",
    category: 'Scholarships',
    tags: ['ALL'],
    urgency: 'Normal',
    postedBy: 'Scholarship Office',
    postedAt: daysAgo(10),
    expiryDate: daysFromNow(32),
    isPinned: false,
    attachmentUrl: null,
    attachmentName: null,
  },
  {
    title: 'Adobe Women-in-Technology Scholarship',
    body: "Adobe is offering scholarships to female students in computing and technology. Open to BBA-IT and BCA students too. Deadline: July 15th. Apply via Adobe portal.",
    category: 'Scholarships',
    tags: ['BBA-IT'],
    urgency: 'Normal',
    postedBy: 'Academic Cell',
    postedAt: daysAgo(5),
    expiryDate: daysFromNow(16),
    isPinned: false,
    attachmentUrl: null,
    attachmentName: null,
  },

  // SPORTS (4)
  {
    title: 'Inter-Department Football Tournament (SAGI Cup)',
    body: "Kick-off for SAGI Cup is July 18th! Departments must submit their final 16-player squad by July 15th. Matches will be held at the Main Sports Ground from 4 PM onwards.",
    category: 'Sports',
    tags: ['ALL'],
    urgency: 'Important',
    postedBy: 'Sports Dept.',
    postedAt: daysAgo(2),
    expiryDate: daysFromNow(21),
    isPinned: false,
    attachmentUrl: null,
    attachmentName: null,
  },
  {
    title: 'University Badminton Selection Trials',
    body: "Trials for the University Men's and Women's Badminton teams will be held on July 12th at the Indoor Court. Report at 8 AM sharp in proper sports kit.",
    category: 'Sports',
    tags: ['ALL'],
    urgency: 'Normal',
    postedBy: 'Sports Dept.',
    postedAt: daysAgo(4),
    expiryDate: daysFromNow(13),
    isPinned: false,
    attachmentUrl: null,
    attachmentName: null,
  },
  {
    title: 'Yoga & Wellness Week - Registration Open',
    body: "Join us for a 7-day health intensive specializing in stress management for exams. Daily at 6:30 AM in the Yoga Hall. Certificate provided upon 100% attendance.",
    category: 'Sports',
    tags: ['ALL'],
    urgency: 'Normal',
    postedBy: 'Wellness Club',
    postedAt: daysAgo(1),
    expiryDate: daysFromNow(12),
    isPinned: false,
    attachmentUrl: null,
    attachmentName: null,
  },
  {
    title: 'State Level Swimming Meet - Call for Athletes',
    body: "Students who have previously won at district level in swimming are invited to join the college training squad for the upcoming State Meet in Gwalior. Meet in the pool area today at 5 PM.",
    category: 'Sports',
    tags: ['ALL'],
    urgency: 'Normal',
    postedBy: 'Sports Dept.',
    postedAt: daysAgo(0),
    expiryDate: daysFromNow(5),
    isPinned: false,
    attachmentUrl: null,
    attachmentName: null,
  },

  // HOSTEL (3)
  {
    title: 'Hostel Outpass: New Automated System',
    body: "Effective July 1st, all outpass requests must be made via the Student App. Manual gate passes will be discontinued. Ensure your parent's contact is verified on the portal.",
    category: 'Hostel',
    tags: ['ALL'],
    urgency: 'Important',
    postedBy: 'Chief Warden',
    postedAt: daysAgo(2),
    expiryDate: daysFromNow(60),
    isPinned: false,
    attachmentUrl: null,
    attachmentName: null,
  },
  {
    title: 'Maintenance Alert: Block B Water Supply',
    body: "Due to overhead tank cleaning, water supply in Hostel Block B will be unavailable on July 6th from 10 AM to 4 PM. Please store water in advance.",
    category: 'Hostel',
    tags: ['ALL'],
    urgency: 'Normal',
    postedBy: 'Maintenance Head',
    postedAt: daysAgo(1),
    expiryDate: daysFromNow(7),
    isPinned: false,
    attachmentUrl: null,
    attachmentName: null,
  },
  {
    title: 'Hostel Night: Theme - Bollywood Retro',
    body: "Our monthly hostel dinner night is back on July 14th! Theme: Bollywood Retro. Best dressed male and female get prize coupons for the college canteen.",
    category: 'Hostel',
    tags: ['ALL'],
    urgency: 'Normal',
    postedBy: 'Hostel Council',
    postedAt: daysAgo(3),
    expiryDate: daysFromNow(15),
    isPinned: false,
    attachmentUrl: null,
    attachmentName: null,
  },

  // GENERAL (3)
  {
    title: 'New Campus Wi-Fi Credentials',
    body: "The campus-wide Wi-Fi network has been upgraded. New SSID: 'SAGI_Secure_5G'. Use your ERP ID and Password to authenticate. Max 2 devices per student.",
    category: 'General',
    tags: ['ALL'],
    urgency: 'Important',
    postedBy: 'IT Helpdesk',
    postedAt: daysAgo(1),
    expiryDate: daysFromNow(90),
    isPinned: false,
    attachmentUrl: null,
    attachmentName: null,
  },
  {
    title: 'Voter Registration Camp on Campus',
    body: "Indore District Election Commission is organizing a 2-day voter registration camp for students who have turned 18. Bring Aadhaar Card and 2 photos. July 22-23 at Library Entrance.",
    category: 'General',
    tags: ['ALL'],
    urgency: 'Normal',
    postedBy: 'Admin Office',
    postedAt: daysAgo(4),
    expiryDate: daysFromNow(24),
    isPinned: false,
    attachmentUrl: null,
    attachmentName: null,
  },
  {
    title: 'Found: Laptop Sleeve (Grey/Dell)',
    body: "A grey Dell laptop sleeve was found in Room 305 yesterday. Owner can claim it from the Security Office by identifying the content or matching the ID card inside.",
    category: 'General',
    tags: ['ALL'],
    urgency: 'Normal',
    postedBy: 'Security Dept.',
    postedAt: daysAgo(1),
    expiryDate: daysFromNow(10),
    isPinned: false,
    attachmentUrl: null,
    attachmentName: null,
  },
];

export const SEED_EVENTS: Omit<CalendarEvent, 'id'>[] = [
  { title: "BBA Sem 8 Commencement", category: "Academic", date: daysFromNow(2), tags: ["BBA-4"], color: "#6366F1", description: "First day of the final semester." },
  { title: "Mid-Sem Examinations", category: "Exam", date: daysFromNow(45), tags: ["ALL"], color: "#EF4444", description: "Mid-semester internal assessment." },
  { title: "HDFC Placement Drive", category: "Placement", date: daysFromNow(15), tags: ["BBA-4"], color: "#10B981", description: "On-campus recruitment for MT roles." },
  { title: "Synopsis Submission", category: "Academic", date: daysFromNow(10), tags: ["BBA-4"], color: "#6366F1", description: "Deadline for research project synopsis." },
  { title: "Case Study Workshop", category: "Placement", date: daysFromNow(18), tags: ["ALL"], color: "#10B981", description: "Inter-departmental workshop." },
  { title: "Aarohan Fest Day 1", category: "Events", date: daysFromNow(30), tags: ["ALL"], color: "#F59E0B", description: "Grand opening of the cultural fest." },
  { title: "Blood Donation Camp", category: "Events", date: daysFromNow(5), tags: ["ALL"], color: "#EF4444", description: "NSS supported drive." },
  { title: "Inter-Dept Football", category: "Sports", date: daysFromNow(12), tags: ["ALL"], color: "#F43F5E", description: "Opening match of SAGI Cup." },
];

export const SEED_ASSIGNMENTS: Omit<Assignment, 'id'>[] = [
  { title: "SWOT Analysis: Indore Startups", course: "Strategic Management (BBA801)", dueDate: daysFromNow(5), tags: ["BBA-4"], description: "Perform a detailed SWOT analysis of any two startups based in Indore. Minimum 2000 words.", postedBy: "Dr. Rajesh Sharma", postedAt: daysAgo(2) },
  { title: "International Trade Policy Review", course: "International Business (BBA802)", dueDate: daysFromNow(12), tags: ["BBA-4"], description: "Critically examine India's new Foreign Trade Policy. Compare with neighboring nations.", postedBy: "Prof. Anita Gupta", postedAt: daysAgo(1) },
  { title: "Case Study: Satyam Scam", course: "Corporate Law & Governance (BBA803)", dueDate: daysFromNow(8), tags: ["BBA-4"], description: "Analyze the governance failures in the Satyam case. 15-page report format.", postedBy: "Prof. Suresh Verma", postedAt: daysAgo(3) },
  { title: "Business Plan: E-Commerce App", course: "Entrepreneurship Dev. (BBA804)", dueDate: daysFromNow(20), tags: ["BBA-4"], description: "Develop a pitch deck and financial model for a hyper-local delivery startup.", postedBy: "Dr. Manish Patel", postedAt: daysAgo(5) },
  { title: "Google Ads Campaign Setup", course: "Digital Marketing (BBA805)", dueDate: daysFromNow(15), tags: ["BBA-4"], description: "Setup a mock Google Ads campaign for a fictional coffee brand. Submit screenshot of keywords and ad copies.", postedBy: "Ms. Priya Joshi", postedAt: daysAgo(2) },
];

export const SEED_USERS: AppUser[] = [
  {
    uid: "admin001",
    email: "admin@dashboard.com",
    name: "Dr. Admin",
    department: "Administration",
    year: 0,
    courses: [],
    isAdmin: true,
    tags: ["ALL"],
    subscribedCategories: ["Academic","Placement","Events","Scholarships","Sports","Hostel","General"],
    fcmToken: null,
    role: 'admin',
    organizationId: 'org-demo',
  },
  {
    uid: "faculty001",
    email: "faculty@dashboard.com",
    name: "Dr. R.K. Sharma",
    department: "School of Management",
    year: 0,
    courses: ["Strategic Management", "International Business"],
    isAdmin: false,
    tags: ["ALL"],
    subscribedCategories: ["Academic","Placement","Events","General"],
    fcmToken: null,
    role: 'faculty',
    organizationId: 'org-demo',
  },
  {
    uid: "student001",
    email: "alice@dashboard.com",
    name: "Alice Sharma",
    department: "School of Management",
    year: 4,
    courses: ["Strategic Management", "International Business", "Corporate Law & Governance", "Entrepreneurship Development", "Digital Marketing", "Project Management"],
    isAdmin: false,
    tags: ["BBA-4", "ALL"],
    subscribedCategories: ["Academic","Placement","Events","Scholarships", "Sports", "Hostel", "General"],
    fcmToken: null,
    role: 'student',
    organizationId: 'org-demo',
  },
  {
    uid: "student002",
    email: "bob@dashboard.com",
    name: "Bob Patel",
    department: "CSE",
    year: 3,
    courses: ["Data Structures","DBMS","Computer Networks"],
    isAdmin: false,
    tags: ["CSE-3", "ALL"],
    subscribedCategories: ["Academic","Placement","Events"],
    fcmToken: null,
    role: 'student',
    organizationId: 'org-demo',
  },
];
