export type UserRole = 'student' | 'admin' | 'faculty' | 'demo';

export type Category =
  | 'Academic'
  | 'Placement'
  | 'Events'
  | 'Scholarships'
  | 'Sports'
  | 'Hostel'
  | 'General';

export type Urgency = 'Normal' | 'Important' | 'Urgent';

export type AssignPriority = 'low' | 'medium' | 'high' | 'urgent';

export type PublishState = 'draft' | 'published';

export interface Notice {
  id: string;
  title: string;
  body: string;
  category: Category;
  tags: string[]; // e.g. ["BBA-4", "BCOM-3", "ALL"]
  urgency: Urgency;
  postedBy: string;
  postedAt: Date;
  expiryDate: Date;
  isPinned: boolean;
  attachmentUrl: string | null;
  attachmentName: string | null;
  // Audit & Control
  publishState?: PublishState;
  createdAt?: Date;
  updatedAt?: Date;
  createdBy?: string;
  updatedBy?: string;
  organizationId: string;
}

export interface CalendarEvent {
  id: string;
  title: string;
  description: string;
  category: string; // "Exam", "Workshop", "Holiday", "Club", "Sports", "Deadline"
  date: Date;
  endDate?: Date;
  tags: string[];
  color: string;
  time?: string;
  location?: string;
  // Audit & Control
  publishState?: PublishState;
  createdAt?: Date;
  updatedAt?: Date;
  createdBy?: string;
  updatedBy?: string;
  organizationId: string;
}

export interface Assignment {
  id: string;
  title: string;
  course: string; // e.g. "Data Structures (CS301)"
  description: string;
  dueDate: Date;
  tags: string[];
  isCompleted?: boolean;
  postedBy: string;
  postedAt: Date;
  priority?: AssignPriority;
  // Audit & Control
  publishState?: PublishState;
  createdAt?: Date;
  updatedAt?: Date;
  createdBy?: string;
  updatedBy?: string;
  organizationId: string;
}

export interface AppUser {
  uid: string;
  email: string;
  name: string;
  department: string;
  year: number;
  courses: string[];
  isAdmin: boolean;
  tags: string[]; // auto-computed: ["CSE-3", "ALL"]
  subscribedCategories: string[];
  fcmToken: string | null;
  readNotices?: string[];
  role?: 'student' | 'admin' | 'faculty';
  organizationId?: string;
}

export interface NormalizedUserProfile {
  id: string;
  fullName: string;
  email: string;
  role: UserRole;
  organizationId?: string;
  department?: string;
  program?: string;
  year?: number;
  semester?: number;
  section?: string;
  rollNumber?: string;
  enrolledCourses: string[];
  customGroups: string[];
  tags: string[]; // Unified tags generated by the targeting engine
}

export interface NoticeFormData {
  title: string;
  body: string;
  category: Category;
  tags: string[];
  urgency: Urgency;
  expiryDate: string;
  isPinned: boolean;
  postedBy: string;
  attachmentUrl: string;
  attachmentName: string;
}
